### ISSUE TITLE
how to setup?

### ISSUE THREAD

**Issue by develperbayman** [aldrin112602/real-time-chat-app#6]
how to setup is there a admin field? ....do i need to setup a DB??

**Comment by aldrin112602** [comment]
Hello thank you so much for your interest, I appreciate it, 
First you need to download the zip file, or just clone the repository.

To setup database connection, install XAMPP, then open htdocs folder located in your xampp folder
move the dowloaded files or folder to htdocs, then open xampp server, click start on both Apache and MySQL
click on both Admin, 
To setup database, create a database :

Database: `mydb`
then click sql and import the files' `My SQL.sql` file from downloaded files, then click `go` button to execute the sql
that's it, you can now use the chat-app 
Please let me know if you have any questions, feel free to ask, I'm willing to help
